// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Norse.Reference.Data.EntityFramework.Migrations.SqlServer.Migrations;

[DbContext(typeof(ReferenceDbContext))]
partial class ReferenceDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260802014858_InitialCreate";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Norse.Reference.Data.EntityFramework.CountryOrArea", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Alpha2")
                    .IsRequired()
                    .HasMaxLength(2)
                    .HasColumnType("nchar(2)")
                    .IsFixedLength();

                b.Property<string>("Alpha3")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("nchar(3)")
                    .IsFixedLength();

                b.Property<byte>("Classification")
                    .HasColumnType("tinyint");

                b.Property<int>("Code")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<Guid?>("ParentRegionId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("Alpha2")
                    .IsUnique();

                b.HasIndex("Alpha3")
                    .IsUnique();

                b.HasIndex("Code")
                    .IsUnique();

                b.HasIndex("ParentRegionId");

                b.ToTable("CountryOrArea");
            });

        modelBuilder.Entity("Norse.Reference.Data.EntityFramework.Region", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("Code")
                    .HasColumnType("int");

                b.Property<byte>("Level")
                    .HasColumnType("tinyint");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<Guid?>("ParentRegionId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("Code")
                    .IsUnique();

                b.HasIndex("ParentRegionId");

                b.ToTable("Region");
            });

        modelBuilder.Entity("Norse.Reference.Data.EntityFramework.CountryOrArea", b =>
            {
                b.HasOne("Norse.Reference.Data.EntityFramework.Region", "ParentRegion")
                    .WithMany("CountriesOrAreas")
                    .HasForeignKey("ParentRegionId");

                b.OwnsOne("Norse.Reference.Data.EntityFramework.CountryOrAreaView", "View", b1 =>
                    {
                        b1.Property<Guid>("CountryOrAreaId");

                        b1.Property<string>("Alpha2")
                            .IsRequired();

                        b1.Property<string>("Alpha3")
                            .IsRequired();

                        b1.Property<byte>("Classification");

                        b1.Property<int>("Code");

                        b1.Property<Guid>("Id");

                        b1.Property<string>("Name")
                            .IsRequired();

                        b1.HasKey("CountryOrAreaId");

                        b1.ToTable("CountryOrArea");

                        b1
                            .ToJson("View")
                            .HasColumnType("json");

                        b1.WithOwner()
                            .HasForeignKey("CountryOrAreaId");

                        b1.OwnsOne("Norse.Reference.Data.EntityFramework.RegionNode", "Region", b2 =>
                            {
                                b2.Property<Guid>("CountryOrAreaViewCountryOrAreaId");

                                b2.Property<string>("Code")
                                    .IsRequired();

                                b2.Property<Guid>("Id");

                                b2.Property<string>("Name")
                                    .IsRequired();

                                b2.HasKey("CountryOrAreaViewCountryOrAreaId");

                                b2.ToTable("CountryOrArea");

                                b2.WithOwner()
                                    .HasForeignKey("CountryOrAreaViewCountryOrAreaId");

                                b2.OwnsOne("Norse.Reference.Data.EntityFramework.SubregionNode", "Subregion", b3 =>
                                    {
                                        b3.Property<Guid>("RegionNodeCountryOrAreaViewCountryOrAreaId");

                                        b3.Property<string>("Code")
                                            .IsRequired();

                                        b3.Property<Guid>("Id");

                                        b3.Property<string>("Name")
                                            .IsRequired();

                                        b3.HasKey("RegionNodeCountryOrAreaViewCountryOrAreaId");

                                        b3.ToTable("CountryOrArea");

                                        b3.WithOwner()
                                            .HasForeignKey("RegionNodeCountryOrAreaViewCountryOrAreaId");

                                        b3.OwnsOne("Norse.Reference.Data.EntityFramework.IntermediateRegionNode", "IntermediateRegion", b4 =>
                                            {
                                                b4.Property<Guid>("SubregionNodeRegionNodeCountryOrAreaViewCountryOrAreaId");

                                                b4.Property<string>("Code")
                                                    .IsRequired();

                                                b4.Property<Guid>("Id");

                                                b4.Property<string>("Name")
                                                    .IsRequired();

                                                b4.HasKey("SubregionNodeRegionNodeCountryOrAreaViewCountryOrAreaId");

                                                b4.ToTable("CountryOrArea");

                                                b4.WithOwner()
                                                    .HasForeignKey("SubregionNodeRegionNodeCountryOrAreaViewCountryOrAreaId");
                                            });

                                        b3.Navigation("IntermediateRegion");
                                    });

                                b2.Navigation("Subregion");
                            });

                        b1.Navigation("Region");
                    });

                b.Navigation("ParentRegion");

                b.Navigation("View")
                    .IsRequired();
            });

        modelBuilder.Entity("Norse.Reference.Data.EntityFramework.Region", b =>
            {
                b.HasOne("Norse.Reference.Data.EntityFramework.Region", "ParentRegion")
                    .WithMany("ChildRegions")
                    .HasForeignKey("ParentRegionId");

                b.Navigation("ParentRegion");
            });

        modelBuilder.Entity("Norse.Reference.Data.EntityFramework.Region", b =>
            {
                b.Navigation("ChildRegions");

                b.Navigation("CountriesOrAreas");
            });
#pragma warning restore 612, 618
    }
}
