// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Norse.Reference.Data;

#nullable disable

namespace Norse.Reference.Data.Migrations.SqlServer.Migrations;

[DbContext(typeof(ReferenceDataDbContext))]
partial class ReferenceDataDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260723130846_InitialCreate";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Norse.Reference.Data.CountryOrArea", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Alpha2")
                    .IsRequired()
                    .HasMaxLength(2)
                    .HasColumnType("nvarchar(2)");

                b.Property<string>("Alpha3")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("nvarchar(3)");

                b.Property<int>("Classification")
                    .HasColumnType("int");

                b.Property<int>("Code")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<Guid?>("ParentRegionId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("Alpha2")
                    .IsUnique();

                b.HasIndex("Alpha3")
                    .IsUnique();

                b.HasIndex("Code")
                    .IsUnique();

                b.HasIndex("ParentRegionId");

                b.ToTable("CountryOrArea");
            });

        modelBuilder.Entity("Norse.Reference.Data.Region", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("Code")
                    .HasColumnType("int");

                b.Property<int>("Level")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<Guid?>("ParentRegionId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("Code")
                    .IsUnique();

                b.HasIndex("ParentRegionId");

                b.ToTable("Region");
            });

        modelBuilder.Entity("Norse.Reference.Data.CountryOrArea", b =>
            {
                b.HasOne("Norse.Reference.Data.Region", "ParentRegion")
                    .WithMany()
                    .HasForeignKey("ParentRegionId");

                b.OwnsOne("Norse.Reference.Data.RegionNode", "View", b1 =>
                    {
                        b1.Property<Guid>("CountryOrAreaId");

                        b1.Property<string>("Code")
                            .IsRequired();

                        b1.Property<string>("Name")
                            .IsRequired();

                        b1.HasKey("CountryOrAreaId");

                        b1.ToTable("CountryOrArea");

                        b1
                            .ToJson("View")
                            .HasColumnType("json");

                        b1.WithOwner()
                            .HasForeignKey("CountryOrAreaId");

                        b1.OwnsOne("Norse.Reference.Data.SubregionNode", "Subregion", b2 =>
                            {
                                b2.Property<Guid>("RegionNodeCountryOrAreaId");

                                b2.Property<string>("Code")
                                    .IsRequired();

                                b2.Property<string>("Name")
                                    .IsRequired();

                                b2.HasKey("RegionNodeCountryOrAreaId");

                                b2.ToTable("CountryOrArea");

                                b2.WithOwner()
                                    .HasForeignKey("RegionNodeCountryOrAreaId");

                                b2.OwnsOne("Norse.Reference.Data.IntermediateRegionNode", "IntermediateRegion", b3 =>
                                    {
                                        b3.Property<Guid>("SubregionNodeRegionNodeCountryOrAreaId");

                                        b3.Property<string>("Code")
                                            .IsRequired();

                                        b3.Property<string>("Name")
                                            .IsRequired();

                                        b3.HasKey("SubregionNodeRegionNodeCountryOrAreaId");

                                        b3.ToTable("CountryOrArea");

                                        b3.WithOwner()
                                            .HasForeignKey("SubregionNodeRegionNodeCountryOrAreaId");
                                    });

                                b2.Navigation("IntermediateRegion");
                            });

                        b1.Navigation("Subregion");
                    });

                b.Navigation("ParentRegion");

                b.Navigation("View");
            });

        modelBuilder.Entity("Norse.Reference.Data.Region", b =>
            {
                b.HasOne("Norse.Reference.Data.Region", "ParentRegion")
                    .WithMany()
                    .HasForeignKey("ParentRegionId");

                b.Navigation("ParentRegion");
            });
#pragma warning restore 612, 618
    }
}
