-- ============================================================
-- AUTO-GENERATED BY EF CORE MIGRATIONS — DO NOT EDIT BY HAND
-- Changes made here will be overwritten on the next migration.
-- Run: dotnet ef migrations add <Name> to update this file.
-- ============================================================
CREATE TABLE region (
    id uuid NOT NULL,
    code integer NOT NULL,
    name character varying(256) NOT NULL,
    level integer NOT NULL,
    parent_region_id uuid,
    CONSTRAINT pk_region PRIMARY KEY (id),
    CONSTRAINT fk_region_region_parent_region_id FOREIGN KEY (parent_region_id) REFERENCES region (id)
);


CREATE TABLE country_or_area (
    id uuid NOT NULL,
    code integer NOT NULL,
    alpha2 character varying(2) NOT NULL,
    alpha3 character varying(3) NOT NULL,
    name character varying(256) NOT NULL,
    parent_region_id uuid,
    classification integer NOT NULL,
    view jsonb,
    CONSTRAINT pk_country_or_area PRIMARY KEY (id),
    CONSTRAINT fk_country_or_area_region_parent_region_id FOREIGN KEY (parent_region_id) REFERENCES region (id)
);


CREATE UNIQUE INDEX ix_country_or_area_alpha2 ON country_or_area (alpha2);


CREATE UNIQUE INDEX ix_country_or_area_alpha3 ON country_or_area (alpha3);


CREATE UNIQUE INDEX ix_country_or_area_code ON country_or_area (code);


CREATE INDEX ix_country_or_area_parent_region_id ON country_or_area (parent_region_id);


CREATE UNIQUE INDEX ix_region_code ON region (code);


CREATE INDEX ix_region_parent_region_id ON region (parent_region_id);


