-- ============================================================
-- AUTO-GENERATED BY EF CORE MIGRATIONS — DO NOT EDIT BY HAND
-- Changes made here will be overwritten on the next migration.
-- Run: dotnet ef migrations add <Name> to update this file.
-- ============================================================
CREATE TABLE [Region] (
    [Id] uniqueidentifier NOT NULL,
    [Code] nvarchar(3) NOT NULL,
    [Name] nvarchar(256) NOT NULL,
    [Level] int NOT NULL,
    [ParentRegionId] uniqueidentifier NULL,
    CONSTRAINT [PK_Region] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_Region_Region_ParentRegionId] FOREIGN KEY ([ParentRegionId]) REFERENCES [Region] ([Id])
);
GO


CREATE TABLE [CountryOrArea] (
    [Id] uniqueidentifier NOT NULL,
    [Code] nvarchar(3) NOT NULL,
    [Alpha2] nvarchar(2) NOT NULL,
    [Alpha3] nvarchar(3) NOT NULL,
    [Name] nvarchar(256) NOT NULL,
    [ParentRegionId] uniqueidentifier NULL,
    [Classification] int NOT NULL,
    [View] nvarchar(max) NULL,
    CONSTRAINT [PK_CountryOrArea] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_CountryOrArea_Region_ParentRegionId] FOREIGN KEY ([ParentRegionId]) REFERENCES [Region] ([Id])
);
GO


CREATE UNIQUE INDEX [IX_CountryOrArea_Alpha2] ON [CountryOrArea] ([Alpha2]);
GO


CREATE UNIQUE INDEX [IX_CountryOrArea_Alpha3] ON [CountryOrArea] ([Alpha3]);
GO


CREATE UNIQUE INDEX [IX_CountryOrArea_Code] ON [CountryOrArea] ([Code]);
GO


CREATE INDEX [IX_CountryOrArea_ParentRegionId] ON [CountryOrArea] ([ParentRegionId]);
GO


CREATE UNIQUE INDEX [IX_Region_Code] ON [Region] ([Code]);
GO


CREATE INDEX [IX_Region_ParentRegionId] ON [Region] ([ParentRegionId]);
GO


