// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Norse.Reference.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Norse.Reference.Data.Migrations.PostgreSQL.Migrations;

[DbContext(typeof(ReferenceDbContext))]
[Migration("20260726192500_InitialCreate")]
partial class _20260726192500_InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Norse.Reference.Data.CountryOrArea", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Alpha2")
                    .IsRequired()
                    .HasMaxLength(2)
                    .HasColumnType("character varying(2)")
                    .HasColumnName("alpha2");

                b.Property<string>("Alpha3")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("character varying(3)")
                    .HasColumnName("alpha3");

                b.Property<byte>("Classification")
                    .HasColumnType("smallint")
                    .HasColumnName("classification");

                b.Property<int>("Code")
                    .HasColumnType("integer")
                    .HasColumnName("code");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("name");

                b.Property<Guid?>("ParentRegionId")
                    .HasColumnType("uuid")
                    .HasColumnName("parent_region_id");

                b.HasKey("Id")
                    .HasName("pk_country_or_area");

                b.HasIndex("Alpha2")
                    .IsUnique()
                    .HasDatabaseName("ix_country_or_area_alpha2");

                b.HasIndex("Alpha3")
                    .IsUnique()
                    .HasDatabaseName("ix_country_or_area_alpha3");

                b.HasIndex("Code")
                    .IsUnique()
                    .HasDatabaseName("ix_country_or_area_code");

                b.HasIndex("ParentRegionId")
                    .HasDatabaseName("ix_country_or_area_parent_region_id");

                b.ToTable("country_or_area");
            });

        modelBuilder.Entity("Norse.Reference.Data.Region", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int>("Code")
                    .HasColumnType("integer")
                    .HasColumnName("code");

                b.Property<byte>("Level")
                    .HasColumnType("smallint")
                    .HasColumnName("level");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("name");

                b.Property<Guid?>("ParentRegionId")
                    .HasColumnType("uuid")
                    .HasColumnName("parent_region_id");

                b.HasKey("Id")
                    .HasName("pk_region");

                b.HasIndex("Code")
                    .IsUnique()
                    .HasDatabaseName("ix_region_code");

                b.HasIndex("ParentRegionId")
                    .HasDatabaseName("ix_region_parent_region_id");

                b.ToTable("region");
            });

        modelBuilder.Entity("Norse.Reference.Data.CountryOrArea", b =>
            {
                b.HasOne("Norse.Reference.Data.Region", "ParentRegion")
                    .WithMany()
                    .HasForeignKey("ParentRegionId")
                    .HasConstraintName("fk_country_or_area_region_parent_region_id");

                b.OwnsOne("Norse.Reference.Data.CountryOrAreaView", "View", b1 =>
                    {
                        b1.Property<Guid>("CountryOrAreaId");

                        b1.Property<string>("Alpha2")
                            .IsRequired();

                        b1.Property<string>("Alpha3")
                            .IsRequired();

                        b1.Property<byte>("Classification");

                        b1.Property<int>("Code");

                        b1.Property<Guid>("Id");

                        b1.Property<string>("Name")
                            .IsRequired();

                        b1.HasKey("CountryOrAreaId");

                        b1.ToTable("country_or_area");

                        b1
                            .ToJson("view")
                            .HasColumnType("jsonb");

                        b1.WithOwner()
                            .HasForeignKey("CountryOrAreaId");

                        b1.OwnsOne("Norse.Reference.Data.RegionNode", "Region", b2 =>
                            {
                                b2.Property<Guid>("CountryOrAreaViewCountryOrAreaId");

                                b2.Property<string>("Code")
                                    .IsRequired();

                                b2.Property<Guid>("Id");

                                b2.Property<string>("Name")
                                    .IsRequired();

                                b2.HasKey("CountryOrAreaViewCountryOrAreaId");

                                b2.ToTable("country_or_area");

                                b2.WithOwner()
                                    .HasForeignKey("CountryOrAreaViewCountryOrAreaId");

                                b2.OwnsOne("Norse.Reference.Data.SubregionNode", "Subregion", b3 =>
                                    {
                                        b3.Property<Guid>("RegionNodeCountryOrAreaViewCountryOrAreaId");

                                        b3.Property<string>("Code")
                                            .IsRequired();

                                        b3.Property<Guid>("Id");

                                        b3.Property<string>("Name")
                                            .IsRequired();

                                        b3.HasKey("RegionNodeCountryOrAreaViewCountryOrAreaId");

                                        b3.ToTable("country_or_area");

                                        b3.WithOwner()
                                            .HasForeignKey("RegionNodeCountryOrAreaViewCountryOrAreaId");

                                        b3.OwnsOne("Norse.Reference.Data.IntermediateRegionNode", "IntermediateRegion", b4 =>
                                            {
                                                b4.Property<Guid>("SubregionNodeRegionNodeCountryOrAreaViewCountryOrAreaId");

                                                b4.Property<string>("Code")
                                                    .IsRequired();

                                                b4.Property<Guid>("Id");

                                                b4.Property<string>("Name")
                                                    .IsRequired();

                                                b4.HasKey("SubregionNodeRegionNodeCountryOrAreaViewCountryOrAreaId");

                                                b4.ToTable("country_or_area");

                                                b4.WithOwner()
                                                    .HasForeignKey("SubregionNodeRegionNodeCountryOrAreaViewCountryOrAreaId");
                                            });

                                        b3.Navigation("IntermediateRegion");
                                    });

                                b2.Navigation("Subregion");
                            });

                        b1.Navigation("Region");
                    });

                b.Navigation("ParentRegion");

                b.Navigation("View")
                    .IsRequired();
            });

        modelBuilder.Entity("Norse.Reference.Data.Region", b =>
            {
                b.HasOne("Norse.Reference.Data.Region", "ParentRegion")
                    .WithMany()
                    .HasForeignKey("ParentRegionId")
                    .HasConstraintName("fk_region_region_parent_region_id");

                b.Navigation("ParentRegion");
            });
#pragma warning restore 612, 618
    }
}
