// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Norse.Reference.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Norse.Reference.Data.Migrations.PostgreSQL.Migrations;

[DbContext(typeof(ReferenceDataDbContext))]
partial class ReferenceDataDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260722235856_InitialCreate";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Norse.Reference.Data.CountryOrArea", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Alpha2")
                    .IsRequired()
                    .HasMaxLength(2)
                    .HasColumnType("character varying(2)")
                    .HasColumnName("alpha2");

                b.Property<string>("Alpha3")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("character varying(3)")
                    .HasColumnName("alpha3");

                b.Property<int>("Classification")
                    .HasColumnType("integer")
                    .HasColumnName("classification");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("character varying(3)")
                    .HasColumnName("code");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("name");

                b.Property<Guid?>("ParentRegionId")
                    .HasColumnType("uuid")
                    .HasColumnName("parent_region_id");

                b.HasKey("Id")
                    .HasName("pk_country_or_area");

                b.HasIndex("Alpha2")
                    .IsUnique()
                    .HasDatabaseName("ix_country_or_area_alpha2");

                b.HasIndex("Alpha3")
                    .IsUnique()
                    .HasDatabaseName("ix_country_or_area_alpha3");

                b.HasIndex("Code")
                    .IsUnique()
                    .HasDatabaseName("ix_country_or_area_code");

                b.HasIndex("ParentRegionId")
                    .HasDatabaseName("ix_country_or_area_parent_region_id");

                b.ToTable("country_or_area");
            });

        modelBuilder.Entity("Norse.Reference.Data.Region", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("character varying(3)")
                    .HasColumnName("code");

                b.Property<int>("Level")
                    .HasColumnType("integer")
                    .HasColumnName("level");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("name");

                b.Property<Guid?>("ParentRegionId")
                    .HasColumnType("uuid")
                    .HasColumnName("parent_region_id");

                b.HasKey("Id")
                    .HasName("pk_region");

                b.HasIndex("Code")
                    .IsUnique()
                    .HasDatabaseName("ix_region_code");

                b.HasIndex("ParentRegionId")
                    .HasDatabaseName("ix_region_parent_region_id");

                b.ToTable("region");
            });

        modelBuilder.Entity("Norse.Reference.Data.CountryOrArea", b =>
            {
                b.HasOne("Norse.Reference.Data.Region", "ParentRegion")
                    .WithMany()
                    .HasForeignKey("ParentRegionId")
                    .HasConstraintName("fk_country_or_area_region_parent_region_id");

                b.OwnsOne("Norse.Reference.Data.RegionNode", "View", b1 =>
                    {
                        b1.Property<Guid>("CountryOrAreaId");

                        b1.Property<string>("Code")
                            .IsRequired();

                        b1.Property<string>("Name")
                            .IsRequired();

                        b1.HasKey("CountryOrAreaId");

                        b1.ToTable("country_or_area");

                        b1
                            .ToJson("view")
                            .HasColumnType("jsonb");

                        b1.WithOwner()
                            .HasForeignKey("CountryOrAreaId");

                        b1.OwnsOne("Norse.Reference.Data.SubregionNode", "Subregion", b2 =>
                            {
                                b2.Property<Guid>("RegionNodeCountryOrAreaId");

                                b2.Property<string>("Code")
                                    .IsRequired();

                                b2.Property<string>("Name")
                                    .IsRequired();

                                b2.HasKey("RegionNodeCountryOrAreaId");

                                b2.ToTable("country_or_area");

                                b2
                                    .ToJson("view")
                                    .HasColumnType("jsonb");

                                b2.WithOwner()
                                    .HasForeignKey("RegionNodeCountryOrAreaId");

                                b2.OwnsOne("Norse.Reference.Data.IntermediateRegionNode", "IntermediateRegion", b3 =>
                                    {
                                        b3.Property<Guid>("SubregionNodeRegionNodeCountryOrAreaId");

                                        b3.Property<string>("Code")
                                            .IsRequired();

                                        b3.Property<string>("Name")
                                            .IsRequired();

                                        b3.HasKey("SubregionNodeRegionNodeCountryOrAreaId");

                                        b3.ToTable("country_or_area");

                                        b3
                                            .ToJson("view")
                                            .HasColumnType("jsonb");

                                        b3.WithOwner()
                                            .HasForeignKey("SubregionNodeRegionNodeCountryOrAreaId");
                                    });

                                b2.Navigation("IntermediateRegion");
                            });

                        b1.Navigation("Subregion");
                    });

                b.Navigation("ParentRegion");

                b.Navigation("View");
            });

        modelBuilder.Entity("Norse.Reference.Data.Region", b =>
            {
                b.HasOne("Norse.Reference.Data.Region", "ParentRegion")
                    .WithMany()
                    .HasForeignKey("ParentRegionId")
                    .HasConstraintName("fk_region_region_parent_region_id");

                b.Navigation("ParentRegion");
            });
#pragma warning restore 612, 618
    }
}
