// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Norse.ReferenceData.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Norse.ReferenceData.Data.Migrations.Migrations
{
    [DbContext(typeof(ReferenceDataDbContext))]
    [Migration("20260705042844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Norse.ReferenceData.Data.CountryOrArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsLandLockedDevelopingCountry")
                        .HasColumnType("boolean")
                        .HasColumnName("is_land_locked_developing_country");

                    b.Property<bool>("IsLeastDevelopedCountry")
                        .HasColumnType("boolean")
                        .HasColumnName("is_least_developed_country");

                    b.Property<bool>("IsSmallIslandDevelopingState")
                        .HasColumnType("boolean")
                        .HasColumnName("is_small_island_developing_state");

                    b.Property<string>("IsoAlpha2Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("iso_alpha2code");

                    b.Property<string>("IsoAlpha3Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("iso_alpha3code");

                    b.Property<string>("M49Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("m49code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentRegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_region_id");

                    b.HasKey("Id")
                        .HasName("pk_country_or_areas");

                    b.HasIndex("IsoAlpha2Code")
                        .IsUnique()
                        .HasDatabaseName("uq_country_or_areas_iso_alpha2_code");

                    b.HasIndex("IsoAlpha3Code")
                        .IsUnique()
                        .HasDatabaseName("uq_country_or_areas_iso_alpha3_code");

                    b.HasIndex("M49Code")
                        .IsUnique()
                        .HasDatabaseName("uq_country_or_areas_m49_code");

                    b.HasIndex("ParentRegionId")
                        .HasDatabaseName("ix_country_or_areas_parent_region_id");

                    b.ToTable("country_or_areas", (string)null);
                });

            modelBuilder.Entity("Norse.ReferenceData.Data.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("M49Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("m49code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentRegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_region_id");

                    b.HasKey("Id")
                        .HasName("pk_regions");

                    b.HasIndex("M49Code")
                        .IsUnique()
                        .HasDatabaseName("uq_regions_m49_code");

                    b.HasIndex("ParentRegionId")
                        .HasDatabaseName("ix_regions_parent_region_id");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("Norse.ReferenceData.Data.CountryOrArea", b =>
                {
                    b.HasOne("Norse.ReferenceData.Data.Region", "ParentRegion")
                        .WithMany()
                        .HasForeignKey("ParentRegionId")
                        .HasConstraintName("fk_country_or_areas_region_parent_region_id");

                    b.OwnsOne("Norse.ReferenceData.Data.RegionNode", "View", b1 =>
                        {
                            b1.Property<Guid>("CountryOrAreaId");

                            b1.Property<string>("Code")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.HasKey("CountryOrAreaId");

                            b1.ToTable("country_or_areas");

                            b1
                                .ToJson("view")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CountryOrAreaId")
                                .HasConstraintName("fk_country_or_areas_country_or_areas_id");

                            b1.OwnsOne("Norse.ReferenceData.Data.SubregionNode", "Subregion", b2 =>
                                {
                                    b2.Property<Guid>("RegionNodeCountryOrAreaId");

                                    b2.Property<string>("Code")
                                        .IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.HasKey("RegionNodeCountryOrAreaId")
                                        .HasName("pk_country_or_areas");

                                    b2.ToTable("country_or_areas");

                                    b2.WithOwner()
                                        .HasForeignKey("RegionNodeCountryOrAreaId")
                                        .HasConstraintName("fk_country_or_areas_country_or_areas_region_node_country_or_area_id");

                                    b2.OwnsOne("Norse.ReferenceData.Data.IntermediateRegionNode", "IntermediateRegion", b3 =>
                                        {
                                            b3.Property<Guid>("SubregionNodeRegionNodeCountryOrAreaId");

                                            b3.Property<string>("Code")
                                                .IsRequired();

                                            b3.Property<string>("Name")
                                                .IsRequired();

                                            b3.HasKey("SubregionNodeRegionNodeCountryOrAreaId")
                                                .HasName("pk_country_or_areas");

                                            b3.ToTable("country_or_areas");

                                            b3.WithOwner()
                                                .HasForeignKey("SubregionNodeRegionNodeCountryOrAreaId")
                                                .HasConstraintName("fk_country_or_areas_country_or_areas_subregion_node_region_node_co");
                                        });

                                    b2.Navigation("IntermediateRegion");
                                });

                            b1.Navigation("Subregion");
                        });

                    b.Navigation("ParentRegion");

                    b.Navigation("View");
                });

            modelBuilder.Entity("Norse.ReferenceData.Data.Region", b =>
                {
                    b.HasOne("Norse.ReferenceData.Data.Region", "ParentRegion")
                        .WithMany()
                        .HasForeignKey("ParentRegionId")
                        .HasConstraintName("fk_regions_regions_parent_region_id");

                    b.Navigation("ParentRegion");
                });
#pragma warning restore 612, 618
        }
    }
}
